name: CI-CD Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
  run: |
    ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "
      git config --global --add safe.directory /home/mario/portfolio &&
      cd ~/portfolio &&
      git pull origin main &&
      sudo docker build -t portfolio . &&
      sudo docker stop portfolio || true &&
      sudo docker rm portfolio || true &&
      sudo docker run -d -p 80:9090 --name portfolio portfolio
    "