name: Deploy Portfolio to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            sudo chown -R mario:mario /home/mario/portfolio

            git config --global --add safe.directory /home/mario/portfolio
            cd /home/mario/portfolio

            git fetch origin
            git reset --hard origin/main

            sudo docker build --no-cache -t portfolio .
            sudo docker stop portfolio || true
            sudo docker rm portfolio || true
            sudo docker run -d -p 80:80 --name portfolio portfolio
          EOF